---
# tasks file for roles/nginx
    - name: 'install epel-release repo'
      yum:
        name: epel-release
        state: present
        
    - name: 'install netstat'
      yum:
        name: net-tools
        state: present

    - name: 'install NGINX server'
      yum:
        name: nginx
        state: present  
      notify:
        - nginx start
        
    - name: 'Copy index.html'
      template:
        src: ../templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: 'Copy default.conf'
      template:
        src: ../templates/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - nginx restart
